#!/usr/bin/env python

# compiz-deskmenu is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# compiz-deskmenu is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author(s): crdlb
# Copyright 2008 Christopher Williams <christopherw@verizon.net> 

import dbus, time

time.sleep(0.1)
interface = 'org.compiz_fusion.deskmenu'
service = 'org.compiz_fusion.deskmenu'

session_bus = dbus.SessionBus()


# show it
obj = session_bus.get_object(interface, '/org/compiz_fusion/deskmenu/menu')
deskmenu = dbus.Interface(obj, interface)
deskmenu.show()

